fieldLayouts:
  0a96f29f-58f5-4ab6-b496-cfecb2024f18:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e8cab5f8-0d4d-4a9e-9288-9d1f4a41f262
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bd5afb63-c7cc-4858-a5da-1d75405d64e6 # Profile Photo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3e04f3f-e63f-4875-85b6-583bc5b902fc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 659310a8-9c84-4690-9b3d-68f12812e678 # Bio
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5dccd8ea-6309-4630-898d-85d6f1fd9224
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 76be61da-ed63-4b24-971a-a2522437e696
        userCondition: null
handle: about
hasTitleField: false
name: About
section: ad02e4c9-13f8-4e43-891c-31c14a2c82e5 # About
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
