dateModified: 1703714586
email:
  fromEmail: patrick.fyhn93@gmail.com
  fromName: tutorial
  transportType: craft\mail\transportadapters\Sendmail
fs:
  hardDisk:
    hasUrls: true
    name: 'Hard Disk'
    settings:
      path: '@webroot/uploads/images'
    type: craft\fs\Local
    url: '@web/uploads/images'
meta:
  __names__:
    0e8eb3c4-447a-4e6e-a846-bb332a6d0480: Summary # Summary
    5bdd9a86-0f73-4c2a-92f7-25ec85f87c49: Blog # Blog
    6ddf0f38-dc73-4212-9841-39d1a9c5acfa: 'Post Categories' # Post Categories
    6f5fa957-d96f-4a29-981a-8129573ffbae: Topics # Topics
    7cd9b9e1-1022-4f5c-93d5-f69fd7c51d5e: About # About
    8f7544b2-6b9b-4d1f-9081-e543efb2b41d: Text # Text
    35fbd2bd-5783-45f1-9c72-2b1d7ad98e91: Image # Image
    63fac480-c3d5-4f5a-a130-7a8fd7d70e77: Thumbnail # Thumbnail
    249f7d43-8af2-47db-9d07-30b443a9fe48: Common # Common
    797c2a8b-e614-4666-8df9-6c0a0d62fa52: Text # Text
    3537e996-bb16-45d8-9b65-7185132589e0: Post # Post
    67743bea-4a55-4b90-bb55-41f55fff3554: Global # Global
    659310a8-9c84-4690-9b3d-68f12812e678: Bio # Bio
    ad02e4c9-13f8-4e43-891c-31c14a2c82e5: About # About
    ad971c07-6adb-4042-bf92-7fcde478105a: Blog # Blog
    b61f8ef1-adb8-426c-8761-0e795f525cd3: About # About
    bd5afb63-c7cc-4858-a5da-1d75405d64e6: 'Profile Photo' # Profile Photo
    bf07e0c5-6dad-4004-a007-44514c403bbe: Description # Description
    c4f3b695-ee66-4ef2-b93d-8357df77e00b: Image # Image
    c9fe2f35-4be2-4693-be2b-ecc922c3dd0b: 'Feature Image' # Feature Image
    d76346fb-4628-4b88-9b6c-116a5a3c9249: tutorial # tutorial
    d8885382-e115-48c8-a180-672013879d3e: 'Site Info' # Site Info
    e8a4b7db-7918-4ded-8611-e314130eeab8: 'Post Content' # Post Content
    ef77e8dd-a710-4edc-a90b-96e1d10abad9: Images # Images
    f73a38d6-e3b3-46db-96ad-aae7b6f110ee: tutorial # tutorial
system:
  edition: solo
  live: true
  name: tutorial
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
