defaultPlacement: end
enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  d76346fb-4628-4b88-9b6c-116a5a3c9249: # tutorial
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: about
type: single
